#!/usr/bin/env python3
"""Render captured terminal output to a self-contained SVG.

Why this exists: a terminal tool's README is judged in about five seconds, and
a wall of fenced text does not survive that. The usual answer is an animated
GIF from a screen recorder, which means a large binary blob nobody can review
in a diff and nobody can regenerate without the same tooling installed.

So the demo is generated from real output instead: run the tool, keep its ANSI
bytes, and turn them into SVG text. The result is a few tens of kilobytes,
renders crisply at any zoom, is diffable, and can be regenerated by anyone
with Python — and because the input is the tool's genuine output, the demo
cannot drift into showing something the tool doesn't actually print.

Every glyph is placed at an explicit x coordinate rather than relying on the
viewer's font metrics. Box-drawing and block characters (the report is full of
both) are exactly where alignment breaks if you let a fallback font decide
advance widths, and a misaligned box is worse than no demo at all.

Usage:
    cargo-depcheck depcheck --top 4 | python3 tools/render-demo.py out.svg --title "cargo depcheck"
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, replace

FONT_SIZE = 13.0
CHAR_WIDTH = 7.8
LINE_HEIGHT = 19.0
PAD_X = 18.0
PAD_TOP = 46.0
PAD_BOTTOM = 18.0
CHROME_HEIGHT = 30.0

BACKGROUND = "#14171b"
CHROME = "#1b1f24"
BORDER = "#2b3038"
DEFAULT_FG = "#d6dae0"
TITLE_FG = "#8b93a1"

# A single palette for both normal and bright variants: the report uses color
# as emphasis, not as an 8-color drawing surface, so bright red and red should
# read as the same "this is bad" red rather than two unrelated hues.
PALETTE = {
    30: "#5b6472", 31: "#f2777a", 32: "#9ecf8a", 33: "#e8b563",
    34: "#6fa8dc", 35: "#c39ac9", 36: "#5fc9c9", 37: DEFAULT_FG,
    90: "#6b7280", 91: "#f58f92", 92: "#b0dba0", 93: "#f0c67d",
    94: "#87b9e8", 95: "#d0b0d5", 96: "#7fd6d6", 97: "#eef1f4",
}

SGR = re.compile(r"\x1b\[([0-9;]*)m")
# Every CSI sequence *except* SGR (final byte `m`), plus OSC strings. The
# character class is A-Z, a-l, n-z: including `m` here would strip the color
# codes before they could be parsed, silently rendering the whole demo in the
# default foreground.
OTHER_ESCAPES = re.compile(r"\x1b\[[0-9;?]*[A-Za-ln-z]|\x1b\][^\x07]*\x07")

XML_ESCAPES = {"&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;"}


@dataclass(frozen=True)
class Style:
    color: str = DEFAULT_FG
    bold: bool = False
    dim: bool = False


def apply_sgr(style: Style, params: str) -> Style:
    # An empty parameter list means SGR 0 — a bare `ESC[m` is a reset.
    codes = [int(p) for p in params.split(";") if p != ""] or [0]
    for code in codes:
        if code == 0:
            style = Style()
        elif code == 1:
            style = replace(style, bold=True)
        elif code == 2:
            style = replace(style, dim=True)
        elif code == 22:
            style = replace(style, bold=False, dim=False)
        elif code == 39:
            style = replace(style, color=DEFAULT_FG)
        elif code in PALETTE:
            style = replace(style, color=PALETTE[code])
    return style


def parse(text: str, strip: str | None = None) -> list[list[tuple[str, Style]]]:
    """Splits ANSI text into lines of (run, style) pairs."""
    text = OTHER_ESCAPES.sub("", text.replace("\r\n", "\n").replace("\r", ""))
    lines: list[list[tuple[str, Style]]] = []
    style = Style()
    drop = re.compile(strip) if strip else None

    for raw_line in text.split("\n"):
        # Progress lines are transient: the tool writes them with a trailing
        # `\r` and overwrites them in place, so a real terminal never shows a
        # spinner alongside the result it was waiting for. Dropping them makes
        # a still image match what a user actually sees, rather than stacking
        # states that only existed one after another.
        if drop is not None and drop.search(SGR.sub("", raw_line)):
            continue
        runs: list[tuple[str, Style]] = []
        position = 0
        for match in SGR.finditer(raw_line):
            chunk = raw_line[position : match.start()]
            if chunk:
                runs.append((chunk, style))
            style = apply_sgr(style, match.group(1))
            position = match.end()
        tail = raw_line[position:]
        if tail:
            runs.append((tail, style))
        lines.append(runs)

    # Blank lines at either end are only empty space in a still image, and
    # dropping progress lines tends to leave the blanks that surrounded them.
    def is_blank(line: list[tuple[str, Style]]) -> bool:
        return not any(run.strip() for run, _ in line)

    while lines and is_blank(lines[-1]):
        lines.pop()
    while lines and is_blank(lines[0]):
        lines.pop(0)
    return lines


def escape(text: str) -> str:
    return "".join(XML_ESCAPES.get(ch, ch) for ch in text)


def render(lines: list[list[tuple[str, Style]]], title: str) -> str:
    columns = max((sum(len(run) for run, _ in line) for line in lines), default = 0)
    width = PAD_X * 2 + columns * CHAR_WIDTH
    height = PAD_TOP + len(lines) * LINE_HEIGHT + PAD_BOTTOM

    out: list[str] = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width:.0f}" height="{height:.0f}" '
        f'viewBox="0 0 {width:.0f} {height:.0f}" font-family="ui-monospace, SFMono-Regular, '
        f'Menlo, Consolas, \'DejaVu Sans Mono\', monospace" font-size="{FONT_SIZE}">',
        f'<rect width="{width:.0f}" height="{height:.0f}" rx="8" fill="{BACKGROUND}" '
        f'stroke="{BORDER}"/>',
        f'<path d="M0 8a8 8 0 0 1 8-8h{width - 16:.0f}a8 8 0 0 1 8 8v{CHROME_HEIGHT - 8:.0f}H0z" '
        f'fill="{CHROME}"/>',
        f'<line x1="0" y1="{CHROME_HEIGHT}" x2="{width:.0f}" y2="{CHROME_HEIGHT}" '
        f'stroke="{BORDER}"/>',
    ]
    for index, color in enumerate(("#f2777a", "#e8b563", "#9ecf8a")):
        out.append(f'<circle cx="{18 + index * 16}" cy="{CHROME_HEIGHT / 2:.0f}" r="4.5" fill="{color}"/>')
    if title:
        out.append(
            f'<text x="{width / 2:.0f}" y="{CHROME_HEIGHT / 2 + 4:.0f}" fill="{TITLE_FG}" '
            f'font-size="11" text-anchor="middle">{escape(title)}</text>'
        )

    for row, line in enumerate(lines):
        if not any(run.strip() for run, _ in line):
            continue
        baseline = PAD_TOP + row * LINE_HEIGHT
        out.append(f'<text y="{baseline:.1f}" xml:space="preserve">')
        column = 0
        for run, style in line:
            if not run.strip():
                column += len(run)
                continue
            # Leading whitespace inside a run shifts the glyphs that follow it,
            # so it advances the column counter but is not emitted.
            stripped = run.lstrip()
            column += len(run) - len(stripped)
            text = stripped.rstrip()
            positions = " ".join(
                f"{PAD_X + (column + offset) * CHAR_WIDTH:.1f}" for offset in range(len(text))
            )
            attributes = [f'x="{positions}"', f'fill="{style.color}"']
            if style.bold:
                attributes.append('font-weight="600"')
            if style.dim:
                attributes.append('opacity="0.6"')
            out.append(f'<tspan {" ".join(attributes)}>{escape(text)}</tspan>')
            column += len(stripped)
        out.append("</text>")

    out.append("</svg>")
    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", help="path to write the SVG to")
    parser.add_argument("--title", default="", help="window chrome title")
    parser.add_argument(
        "--input",
        help="read captured output from this file instead of stdin",
    )
    parser.add_argument(
        "--strip",
        help="regular expression; matching lines are dropped (for transient progress output)",
    )
    args = parser.parse_args()

    if args.input:
        with open(args.input, "r", encoding="utf-8", errors="replace") as handle:
            captured = handle.read()
    else:
        captured = sys.stdin.read()

    if not captured.strip():
        print("render-demo: no input captured", file=sys.stderr)
        return 1

    svg = render(parse(captured, args.strip), args.title)
    with open(args.output, "w", encoding="utf-8") as handle:
        handle.write(svg)
    print(f"wrote {args.output} ({len(svg) / 1024:.1f} KiB)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
